services:
  php:
    image: php:8.2-fpm
    container_name: symfony_php
    volumes:
      - ./:/var/www/html
      - ./var:/var/www/html/var 
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - symfony

networks:
  symfony:

volumes:
  mysql_data:
